# Generated by Django 5.2.1 on 2025-05-21 18:25

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        db_index=True,
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("username", models.CharField(max_length=25, unique=True)),
                (
                    "email",
                    models.EmailField(
                        max_length=255, unique=True, verbose_name="Email"
                    ),
                ),
                (
                    "account_type",
                    models.CharField(
                        choices=[
                            ("regular", "Regular"),
                            ("silver", "Silver"),
                            ("gold", "Gold"),
                            ("platinum", "Platinum"),
                        ],
                        default="regular",
                        max_length=10,
                    ),
                ),
                ("name", models.CharField(max_length=255, null=True)),
                ("password", models.CharField(max_length=255)),
                ("address", models.CharField(max_length=500, null=True)),
                (
                    "pincode",
                    models.CharField(default="713216", max_length=6, null=True),
                ),
                ("lat", models.CharField(max_length=20, null=True)),
                ("lan", models.CharField(max_length=20, null=True)),
                ("dob", models.DateField(null=True)),
                ("phone", models.CharField(max_length=10, null=True)),
                ("image", models.CharField(max_length=2555, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_deleted", models.BooleanField(default=False)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
